# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/vrvuser/Book-System

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/vrvuser/Book-System

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vrvuser/Book-System/CMakeFiles /home/vrvuser/Book-System/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vrvuser/Book-System/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named book

# Build rule for target.
book: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 book
.PHONY : book

# fast build rule for target.
book/fast:
	$(MAKE) -f CMakeFiles/book.dir/build.make CMakeFiles/book.dir/build
.PHONY : book/fast

#=============================================================================
# Target rules for targets named heart

# Build rule for target.
heart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 heart
.PHONY : heart

# fast build rule for target.
heart/fast:
	$(MAKE) -f CMakeFiles/heart.dir/build.make CMakeFiles/heart.dir/build
.PHONY : heart/fast

module-src/book_module.o: module-src/book_module.cpp.o

.PHONY : module-src/book_module.o

# target to build an object file
module-src/book_module.cpp.o:
	$(MAKE) -f CMakeFiles/book.dir/build.make CMakeFiles/book.dir/module-src/book_module.cpp.o
.PHONY : module-src/book_module.cpp.o

module-src/book_module.i: module-src/book_module.cpp.i

.PHONY : module-src/book_module.i

# target to preprocess a source file
module-src/book_module.cpp.i:
	$(MAKE) -f CMakeFiles/book.dir/build.make CMakeFiles/book.dir/module-src/book_module.cpp.i
.PHONY : module-src/book_module.cpp.i

module-src/book_module.s: module-src/book_module.cpp.s

.PHONY : module-src/book_module.s

# target to generate assembly for a file
module-src/book_module.cpp.s:
	$(MAKE) -f CMakeFiles/book.dir/build.make CMakeFiles/book.dir/module-src/book_module.cpp.s
.PHONY : module-src/book_module.cpp.s

module-src/book_servlet.o: module-src/book_servlet.cpp.o

.PHONY : module-src/book_servlet.o

# target to build an object file
module-src/book_servlet.cpp.o:
	$(MAKE) -f CMakeFiles/book.dir/build.make CMakeFiles/book.dir/module-src/book_servlet.cpp.o
.PHONY : module-src/book_servlet.cpp.o

module-src/book_servlet.i: module-src/book_servlet.cpp.i

.PHONY : module-src/book_servlet.i

# target to preprocess a source file
module-src/book_servlet.cpp.i:
	$(MAKE) -f CMakeFiles/book.dir/build.make CMakeFiles/book.dir/module-src/book_servlet.cpp.i
.PHONY : module-src/book_servlet.cpp.i

module-src/book_servlet.s: module-src/book_servlet.cpp.s

.PHONY : module-src/book_servlet.s

# target to generate assembly for a file
module-src/book_servlet.cpp.s:
	$(MAKE) -f CMakeFiles/book.dir/build.make CMakeFiles/book.dir/module-src/book_servlet.cpp.s
.PHONY : module-src/book_servlet.cpp.s

module-src/heart_module.o: module-src/heart_module.cpp.o

.PHONY : module-src/heart_module.o

# target to build an object file
module-src/heart_module.cpp.o:
	$(MAKE) -f CMakeFiles/heart.dir/build.make CMakeFiles/heart.dir/module-src/heart_module.cpp.o
.PHONY : module-src/heart_module.cpp.o

module-src/heart_module.i: module-src/heart_module.cpp.i

.PHONY : module-src/heart_module.i

# target to preprocess a source file
module-src/heart_module.cpp.i:
	$(MAKE) -f CMakeFiles/heart.dir/build.make CMakeFiles/heart.dir/module-src/heart_module.cpp.i
.PHONY : module-src/heart_module.cpp.i

module-src/heart_module.s: module-src/heart_module.cpp.s

.PHONY : module-src/heart_module.s

# target to generate assembly for a file
module-src/heart_module.cpp.s:
	$(MAKE) -f CMakeFiles/heart.dir/build.make CMakeFiles/heart.dir/module-src/heart_module.cpp.s
.PHONY : module-src/heart_module.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... book"
	@echo "... rebuild_cache"
	@echo "... heart"
	@echo "... module-src/book_module.o"
	@echo "... module-src/book_module.i"
	@echo "... module-src/book_module.s"
	@echo "... module-src/book_servlet.o"
	@echo "... module-src/book_servlet.i"
	@echo "... module-src/book_servlet.s"
	@echo "... module-src/heart_module.o"
	@echo "... module-src/heart_module.i"
	@echo "... module-src/heart_module.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

